apiVersion: V1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-18-homework
    environment: prod
    version: 1.0.0
  name: user-18-homework
  namespace: user-18-homework
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: prod
      version: 1.0.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-18-homework
    spec:
      containers:
      - image: ronaldshao/user-18-ronaldshao:1.0.4
        imagePullPolicy: IfNotPresent
        name: foo
        env:
        - name: foo
          value: "192.168.0.1"
        - name : foo
          value: foo
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"    
        readinessProbe:
          httpGet:
            port: 80
            httpHeaders:
              - name: kubelet-probe
                value: "true"
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
